language: python

python:
  - 2.7
  - 3.6

env:
  - TASK=check
  - TASK=docs
  - TASK=codecov

install: echo "Installing... $TASK"
script: echo "Scripting... $TASK"

jobs:
  include:
    - stage: check
      install: echo "Checking... install $TASK"
      script: echo "Checking... script $TASK"
      python: 3.6
      env: TASK=check
    - stage: docs
      install: echo "Docsing... install $TASK"
      script: echo "Docsing... script $TASK"
      python: 3.6
      env: TASK=check
    - stage: codecov
      install: echo "Codecoving... install $TASK"
      script: echo "Codecoving... script $TASK"
      env: TASK=codecov
