language: python

matrix:
  include:
    - env: TOXENV=check
      python: 3.6
    - env: TOXENV=py27,codecov
      python: 2.7
    - env: TOXENV=py36,codecov
      python: 3.6

stage: test
install: echo "test install (TOXENV=$TOXENV)"
script: echo "test script (TOXENV=$TOXENV)"
