language: python

matrix:
  include:
    - env: TOXENV=check
      python: 3.6
    - env: TOXENV=docs
      python: 3.6
    - env: TOXENV=py26,codecov
      python: 2.6
    - env: TOXENV=py27,codecov
      python: 2.7
    - env: TOXENV=py34,codecov
      python: 3.4
    - env: TOXENV=py35,codecov
      python: 3.5
    - env: TOXENV=py36,codecov
      python: 3.6
    - env: TOXENV=pypy,codecov
      python: pypy

stage: test
install:
  - echo "test install (TOXENV=$TOXENV)"
script:
  - echo "test script (TOXENV=$TOXENV)"

jobs:
  include:
    - stage: check
      install: echo "Check install (TOXENV=$TOXENV)"
      script: echo "Check script (TOXENV=$TOXENV)"
      python: 3.6