language: python

python:
  - 2.7
  - 3.6

env:
  global:
    - BAR="123"

env:
  - FOO=foo
  - FOO=bar

jobs:
  include:
    - install: echo "install- BAR=$BAR"
      script: echo "script- FOO=$FOO"
