language: python

python:
  - 2.7
  - 3.6

install: 
  - echo "Codecov..."
  - echo "Installing... $TASK"
script: echo "Scripting... $TASK"

stages:
  - check
  - docs
  - test

jobs:
  include:
    - stage: check
      install: echo "Checking... install $TASK"
      script: echo "Checking... script $TASK"
      python: 3.6
    - stage: docs
      install: echo "Docsing... install $TASK"
      script: echo "Docsing... script $TASK"
      python: 3.6

