language: python

python:
  - 2.7
  - 3.6

env:
  - BAR=bar
  - FOO=123

stages:
  - deploy

jobs:
  include:
    - stage: deploy
      install: echo "install- BAR=$BAR"
      script: echo "script- FOO=$FOO"
