language: python
stages:
- check
- test
- deploy

python: 
- 2.7
- 3.6
stage: test
install: echo "test install (TOXENV=$TOXENV)"
script: echo "test script (TOXENV=$TOXENV)"

jobs:
  include:
  - stage: check
    install: echo "Check install (TOXENV=$TOXENV)"
    script: echo "Check script (TOXENV=$TOXENV)"
    python: 3.6
  - stage: deploy
    install: echo "Deploy 1 install (TOXENV=$TOXENV)"
    script: echo "Deploy 1 script (TOXENV=$TOXENV)"
    python: 3.6
  - stage: deploy
    install: echo "Deploy 2 install (TOXENV=$TOXENV)"
    script: echo "Deploy 2 script (TOXENV=$TOXENV)"
    python: 3.6
    