language: python

stages:
  - check
  - docs
  - test

jobs:
  include:
    - stage: check
      install: echo "Checking... install $TASK"
      script: echo "Checking... script $TASK"
      python: 3.6
    - stage: docs
      install: echo "Docsing... install $TASK"
      script: echo "Docsing... script $TASK"
      python: 3.6
    - stage: test
      install: echo "Testing... install"
      script: echo "Testing... script"
      python:
        - 2.7
        - 3.4
        - 3.5
