language: python
stages:
- check
- inheriter
- test
- deploy

python: 
- 2.7
- 3.6
- pypy3
stage: test
install: 
  - echo "outer (test) install"
  - pip install --editable .
script: 
  - echo "outer (test) script"
  - env
  - rando
after_failure: echo "outer (test) failure"

jobs:
  include:
  - stage: inheriter
  - stage: check
    install:
      - echo "check install"
      - sed -i -E "s/^(version = )([0-9]+\.[0-9]+\.[0-9]+).*$/\1\2.dev.$sha/" setup.cfg
      - cat setup.cfg
    script: echo "check script"
    python: 3.6
  - stage: deploy
    install: echo "deploy 1 install"
    script: echo "deploy 1 script"
    python: 3.6
  - stage: deploy
    install: echo "deploy 2 install"
    script: echo "deploy 2 script"
    python: 3.6
    