version: '{branch}-{build}'
build: off
image: Visual Studio 2013
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  global:
    WITH_ENV: 'cmd /E:ON /V:ON /C .\ci\run_with_env.cmd'

init:
  - ps: echo "Linear AppVeyor!"
  - set
test_script:
  - dir
  - ps: ls $env:APPVEYOR_BUILD_FOLDER
  - ps: >-
      if($env:APPVEYOR_REPO_BRANCH -eq "master") {
        # sed equivalent
        # sed -i -E "s/^(version = )([0-9]+\.[0-9]+\.[0-9]+).*/\1\2.dev$sha/" $TRAVIS_BUILD_DIR/setup.cfg
        # "([a-z]+)\s([a-z]+)",'$2, $1'
        $ver = (git show -s --format=%cd --date=format:'%Y%m%d%H%M%S')
        (Get-Content setup.cfg) -replace '^(version = )(\d+\.\d+\.\d+).*$', ('$1$2.dev' + $ver) | Set-Content setup.cfg
        Write-Host (Get-Content setup.cfg)
      }
  - set TOXENV=check
  - set PYTHON_HOME=C:\Python36-x64
  - set PYTHON_VERSION=3.6
  - set PYTHON_ARCH=64
  - '%PYTHON_HOME%\Scripts\pip install --upgrade tox setuptools virtualenv wheel'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
  - '%WITH_ENV% %PYTHON_HOME%\Scripts\tox -v'

  - set TOXENV=docs
  - set PYTHON_HOME=C:\Python36-x64
  - set PYTHON_VERSION=3.6
  - set PYTHON_ARCH=64
  - '%PYTHON_HOME%\Scripts\pip install --upgrade tox setuptools virtualenv wheel'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
  - '%WITH_ENV% %PYTHON_HOME%\Scripts\tox -v'

  - set TOXENV=2.7,codecov
  - set PYTHON_HOME=C:\Python27
  - set PYTHON_VERSION=2.7
  - set PYTHON_ARCH=32
  - '%PYTHON_HOME%\Scripts\pip install --upgrade tox setuptools virtualenv wheel'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
  - '%WITH_ENV% %PYTHON_HOME%\Scripts\tox -v'

  - set TOXENV=2.7,codecov
  - set PYTHON_HOME=C:\Python27-x64
  - set PYTHON_VERSION=2.7
  - set PYTHON_ARCH=64
  - '%PYTHON_HOME%\Scripts\pip install --upgrade tox setuptools virtualenv wheel'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
  - '%WITH_ENV% %PYTHON_HOME%\Scripts\tox -v'

  - set TOXENV=3.6,codecov
  - set PYTHON_HOME=C:\Python36
  - set PYTHON_VERSION=3.6
  - set PYTHON_ARCH=32
  - '%PYTHON_HOME%\Scripts\pip install --upgrade tox setuptools virtualenv wheel'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
  - '%WITH_ENV% %PYTHON_HOME%\Scripts\tox -v'

  - set TOXENV=3.6,codecov
  - set PYTHON_HOME=C:\Python36-x64
  - set PYTHON_VERSION=3.6
  - set PYTHON_ARCH=64
  - '%PYTHON_HOME%\Scripts\pip install --upgrade tox setuptools virtualenv wheel'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
  - '%WITH_ENV% %PYTHON_HOME%\Scripts\tox -v'
