version: '{branch}-{build}'
build: off
image: Visual Studio 2013
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  global:
    WITH_ENV: 'cmd /E:ON /V:ON /C .\ci\run_with_env.cmd'

init:
  - ps: echo "Linear AppVeyor!"
  - set
  - ps: >-
      if($env:APPVEYOR_REPO_BRANCH -eq "master") {
        # sed equivalent
        # sed -i -E "s/^(version = )([0-9]+\.[0-9]+\.[0-9]+).*/\1\2.dev$sha/" $TRAVIS_BUILD_DIR/setup.cfg
        # "([a-z]+)\s([a-z]+)",'$2, $1'
        $sha = ($env:APPVEYOR_REPO_COMMIT).Substring(0,7)
        Write-Host "Sha - $sha"
        (Get-Content setup.cfg).replace("(version = )(\d+\.\d+\.\d+).*", '$1$2.dev$sha') | Set-Content setup.cfg
        Write-Host "Setup:" + (Get-Content setup.cfg)
      }  
test_script:
  - set TOXENV=check
  - set PYTHON_HOME=C:\Python36-x64
  - set PYTHON_VERSION=3.6
  - set PYTHON_ARCH=64
  - '%PYTHON_HOME%\Scripts\pip install --upgrade tox setuptools virtualenv wheel'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
  - '%WITH_ENV% %PYTHON_HOME%\Scripts\tox -v'

  - set TOXENV=docs
  - set PYTHON_HOME=C:\Python36-x64
  - set PYTHON_VERSION=3.6
  - set PYTHON_ARCH=64
  - '%PYTHON_HOME%\Scripts\pip install --upgrade tox setuptools virtualenv wheel'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
  - '%WITH_ENV% %PYTHON_HOME%\Scripts\tox -v'

  - set TOXENV=2.7,codecov
  - set PYTHON_HOME=C:\Python27
  - set PYTHON_VERSION=2.7
  - set PYTHON_ARCH=32
  - '%PYTHON_HOME%\Scripts\pip install --upgrade tox setuptools virtualenv wheel'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
  - '%WITH_ENV% %PYTHON_HOME%\Scripts\tox -v'

  - set TOXENV=2.7,codecov
  - set PYTHON_HOME=C:\Python27-x64
  - set PYTHON_VERSION=2.7
  - set PYTHON_ARCH=64
  - '%PYTHON_HOME%\Scripts\pip install --upgrade tox setuptools virtualenv wheel'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
  - '%WITH_ENV% %PYTHON_HOME%\Scripts\tox -v'

  - set TOXENV=3.6,codecov
  - set PYTHON_HOME=C:\Python36
  - set PYTHON_VERSION=3.6
  - set PYTHON_ARCH=32
  - '%PYTHON_HOME%\Scripts\pip install --upgrade tox setuptools virtualenv wheel'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
  - '%WITH_ENV% %PYTHON_HOME%\Scripts\tox -v'

  - set TOXENV=3.6,codecov
  - set PYTHON_HOME=C:\Python36-x64
  - set PYTHON_VERSION=3.6
  - set PYTHON_ARCH=64
  - '%PYTHON_HOME%\Scripts\pip install --upgrade tox setuptools virtualenv wheel'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
  - '%WITH_ENV% %PYTHON_HOME%\Scripts\tox -v'
